[phases.setup]
nixPkgs = ["nodejs-20", "python38"]

[phases.install]
cmds = [
  "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "pip install -r requirements.txt",
  "mkdir -p backend/data"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
