[providers]
node = "20"
python = "3.8"

[phases.build]
cmds = [
    "cd frontend && npm ci && npm run build && cd ..",
    "pip install -r requirements.txt",
    "mkdir -p backend/data"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"