[phases.setup]
nixPkgs = ["nodejs-20_x", "python38", "python38Packages.pip"]

[phases.build]
cmds = [
    "cd frontend && npm ci && npm run build && cd ..",
    "pip install -r requirements.txt",
    "mkdir -p backend/data"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"