[build]
builder = "nixpacks"
buildCommand = """
cd frontend && npm ci && npm run build && cd ..
pip install -r requirements.txt
mkdir -p backend/data
"""

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"

[env]
PORT = { default = "8000" }
PYTHON_VERSION = "3.8"
PYTHONPATH = "."
OPENROUTER_API_KEY = { widget = "text" }
PINECONE_API_KEY = { widget = "text" }
PINECONE_INDEX_NAME = { default = "offer-letter-index" }
PINECONE_CLOUD = { default = "aws" }
PINECONE_REGION = { default = "us-west-2" }
