[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd .. && pip install -r requirements.txt && mkdir -p backend/data"

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[env]
PYTHONPATH = "."
PYTHON_VERSION = "3.8"  
OPENROUTER_API_KEY = { widget = "text" }
PINECONE_API_KEY = { widget = "text" }
PINECONE_INDEX_NAME = { widget = "text", default = "offer-letter-index" }
PINECONE_CLOUD = { widget = "text", default = "aws" }
PINECONE_REGION = { widget = "text", default = "us-west-2" }